In [1]:
import pandas as pd

In [2]:
df_games = pd.read_parquet(r'C:\Users\Owner\Desktop\LABS\Proyecto_STEAM\datos_STEAM\parquet\games_clean.parquet')

In [3]:
df_games

,id,app_name,developer,genres,price,release_date,tags
0,761140,Lost Summoner Kitty,Kotoshiro,Action,4.99,2018-01-04,"[Strategy, Action, Indie, Casual, Simulation]"
1,643980,Ironbound,Secret Level SRL,Indie,NaN,2018-01-04,"[Free to Play, Strategy, Indie, RPG, Card Game..."
2,670290,Real Pool 3D - Poolians,Poolians.com,Casual,NaN,2017-07-24,"[Free to Play, Simulation, Sports, Casual, Ind..."
3,767400,弹炸人2222,彼岸领域,Action,0.99,2017-12-07,"[Action, Adventure, Casual]"
4,773570,Log Challenge,None,Action,2.99,None,"[Action, Indie, Casual, Sports]"
...,...,...,...,...,...,...,...
32130,773640,Colony On Mars,"Nikita ""Ghost_RUS""",Casual,1.99,2018-01-04,"[Strategy, Indie, Casual, Simulation]"
32131,733530,LOGistICAL: South Africa,Sacada,Casual,4.99,2018-01-04,"[Strategy, Indie, Casual]"
32132,610660,Russian Roads,Laush Dmitriy Sergeevich,Indie,1.99,2018-01-04,"[Indie, Simulation, Racing]"
32133,658870,EXIT 2 - Directions,"xropi,stev3ns",Casual,4.99,2017-09-02,"[Indie, Casual, Puzzle, Singleplayer, Atmosphe..."
32134,681550,Maze Run VR,None,Early Access,4.99,None,"[Early Access, Adventure, Indie, Action, Simul..."

In [4]:
import pandas as pd


# Assuming your DataFrame is named 'df_games'

# Explode genres, create dummies, and sum by game id
genres_dummies = (
    df_games['genres'].explode()
    .str.get_dummies()
    .groupby(level=0)
    .sum()
    .reset_index(drop=True)
)

# Combine game id with genre dummies
all_genres = pd.concat([df_games[['id']], genres_dummies], axis=1)

# Identify columns to keep (excluding those with any case of "&amp;")
keep_cols = all_genres.columns[~all_genres.columns.str.contains('&amp;', case=False)]

# Filter DataFrame to keep desired columns
all_genres = all_genres[keep_cols]

# Ensure unique column names (if necessary)
all_genres.columns = pd.unique(all_genres.columns)

all_genres

,id,360 Video,Accounting,Action,Adventure,Animation & Modeling,Anime,Arcade,Audio Production,Beat 'em up,...,Tutorial,Twin Stick Shooter,Utilities,VR,Video Production,Violent,War,Web Publishing,World War II,Zombies
0,761140,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,643980,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,670290,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,767400,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,773570,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32130,773640,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
32131,733530,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
32132,610660,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
32133,658870,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
32134,681550,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [5]:
all_genres.to_parquet(r'C:\Users\Owner\Desktop\LABS\Proyecto_STEAM\datos_STEAM\parquet\df_dummies.parquet', index=False)